### ISSUE TITLE
Update goatherd checklist to make actions more explicit

### ISSUE THREAD

**Issue by cassgvp** [alan-turing-institute/open-research-community-management#256]
### Summary Sentence

In TPS we use "goatherd" to refer to the person nominated to chair and facilitate weekly meetings. In the RCM team, the "goatherd checklist" lists the actions required of the goatherd. Some of these actions are could be made more explicit, and others are missing.

### What needs to be done?

Update the checklist. Starting suggestion below.

- [ ] **Thursday**: Review the goatherder schedule for the assigned meeting type ("TPS CM meeting" or "Theme").
- [ ] **Thursday**: Send a summary of the meeting agenda on slack to #tps-cms-only (TPS CM meeting) or #tps-community-managers-and-collabs (Theme disucssussion). Flag any actions, e.g. to add agenda items.
- [ ] **Thursday**: Personally check in with the speakers and make sure they know what they will be presenting.
- [ ] **Monday (team meeting)**: Chair the team meeting call and ensure notes are taken.
    - [ ] If Theme discussion meeting there will be a space for project updates. Read these out during the meeting, and invite short questions to the project owner.
- [ ] **Monday**: Push / copy call notes hackmd to [project resources](https://github.com/alan-turing-institute/open-research-community-management/tree/main/project-management/team-meetings)
    - [ ] Modify syntax of "info" section to quote block
    - [ ] Redact confidential or identifiable informaton whch was not offered directly by the person identified.
    - [ ] Redact zoom links and meeting id etc.
    - [ ] Redact links to list-of-links and goatherd schedule at the bottom (redacted as this links to previous meeting notes which have not been reviewed for confidentiality)
    - [ ] Tag previous and next weeks goatherd for PR review
- [ ] **Monday or after PR merged**: Share link to notes on the appropriate slack channel for the meeting. Flag any actions/issues.
- [ ] **Wednesday (co-working)**: Chair the co-working call
    - [ ] Ask what people want to work on (folks will often have discussed between them in advance and have suggestions, or they will come to the call ready to contribute anywhere)
    - [ ] Make zoom breakout rooms as required
    - [ ] ANY OTHER CHAIRS ACTIONS? Pomodoro? Calling back to main room?
- [ ] **Wednesday**: Let the next goatherder know that you are passing the responsibility to them - tag them on slack or connect during co-working.

### Who can help?

All rcms!

---

### Update after the issue was opened

[Add details]

**Comment by cassgvp** [comment]
Following my first goatherd, I've suggested above a few updates to the goatherd checklist :). 

@malvikasharan is there anything I've missed? Particularly on links that should be redacted before publishing?

@aleesteele @eirini-zormpa (as previous and next goatherd!) and @EKaroune, have I captured all the chair's actions for team meeting and co-working? Anything else you'd like to add or alter?

**Comment by eirini-zormpa** [comment]
thank you for this @cassgvp, I think it's really helpful :rocket:

**Comment by cassgvp** [comment]
I've updated the goatherd checklist with the above (using "rcm" in place of "cm"), so now closing the issue :)
